# Welcome to Jekyll!
#

# Site settings
title: Four authors. One future.
description: |
Welcome to 2054, 
where memory hackers carve up your mind, 
sex bots lurk behind every corner, 
and the religious wear impenetrable skins.
 
Explore the ocean depths with AI-enhanced octopods. 
Learn your past might not be what you remember. 
Take a bot into your marriage bed, and fall in love across an impenetrable divide.

owner: project2054
first_published: 2018 # if migrating another site, the year of your first publish
email: project2054@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://project2054.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
